version: 2.1

# Thanks to https://github.com/teppeis-sandbox/circleci2-multiple-node-versions

commands:
  test-nodejs:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test

jobs:
  node-v12:
    docker:
      - image: node:12
    steps:
      - test-nodejs
  node-v14:
    docker:
      - image: node:14
    steps:
      - test-nodejs
  node-v16:
    docker:
      - image: node:16
    steps:
      - test-nodejs
  node-v18:
    docker:
      - image: node:18
    steps:
      - test-nodejs

workflows:
  node-multi-build:
    jobs:
      - node-v12
      - node-v14
      - node-v16
      - node-v18
